apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin
  name: {{ .Values.admin.name }}
spec:
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      serviceAccountName: {{ include "easyid-kubernetes.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
            - name: ADMIN_JAVA_OPTS
              value: '{{ .Values.admin.javaOpts }}'
            - name: EMAIL_FROM
              value: '{{ .Values.admin.emailFrom }}'
            - name: EMAIL_HOST
              value: '{{ .Values.admin.emailHost }}'
            - name: EMAIL_PASSWORD
              value: '{{ .Values.admin.emailPassword }}'
            - name: EMAIL_USERNAME
              value: '{{ .Values.admin.emailUsername }}'
            - name: ENABLE_EMAIL_SERVER
              value: '{{ .Values.admin.enableEmail }}'
            - name: POSTGRES_PASSWORD
              value: '{{ .Values.postgres.db_password }}'
            - name: POSTGRES_URL
              value: 'jdbc:postgresql://{{ .Values.postgres.name }}:{{ .Values.postgres.db_port }}/{{ .Values.postgres.db_name }}'
            - name: POSTGRES_USER
              value: '{{ .Values.postgres.db_user }}'
            - name: SPRING_PROFILES_ACTIVE
              value: 'dev'
            - name: MAX_FILE_SIZE
              value: {{.Values.global.max_file_size}}
            - name: MAX_REQUEST_SIZE
              value: {{.Values.global.max_request_size}}B
          image: '{{ .Values.global.registry }}{{ .Values.admin.repository }}:{{ .Values.admin.tag }}'
          ports:
          - containerPort: 8080
          name: {{ .Values.admin.name }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.admin.name }}
spec:
  type: ClusterIP
  selector:
      app: admin
  ports:
  - port: {{ .Values.admin.port }}
    targetPort: 8080
